CREATE TABLE Person(
                       id int primary key generated by default as identity,
                       username varchar(255) not null unique,
                       email varchar(255) not null unique,
                       password varchar(255) not null,
                       role varchar(100),
                       reset_password_token varchar(100)
)